void 0===window.NVS&&(window.NVS={});
(function(g,b,d){var h=[].forEach;d.Carousel=function(a){this._carousel=a;this._items=this._carousel.getElementsByClassName("items")[0];this._controls=this._carousel.getElementsByClassName("controls")[0];this._bubbles=this._controls.getElementsByClassName("bubbles")[0];this._bubbleNodeList=Array.prototype.slice.call(this._bubbles.children);this._itemsLength=this._items.length;this._timeout=0;this.touchStart={x:0,y:0};this.touchEnd={x:0,y:0};this.autoplay=this._carousel.hasAttribute("data-autoplay")&&this._carousel.getAttribute("data-autoplay")!==
"false";this.delay=this._carousel.getAttribute("data-delay")};d.Carousel.prototype.afterTransition=function(){var a=this._items.getElementsByClassName("old-current")[0],c=this._items.getElementsByClassName("current")[0];a&&a.classList.remove("old-current");b.transitionEnd&&c.removeEventListener(b.transitionEnd,this.afterTransition,false);if(this.autoplay){b.clearTimeout(this._timeout);this._timeout=b.setTimeout(this.next.bind(this),this.delay)}};d.Carousel.prototype.goTo=function(a,c){var e=this._items.getElementsByClassName("current")[0];
b.clearTimeout(this._timeout);if(!this._items.getElementsByClassName("old-current").length||!(this._items.getElementsByClassName("old-current").length==1||typeof this._items.getElementsByClassName("old-current")[0].id!=="undefined")){e.classList.add("old-current");e.classList.remove("current");this._bubbles.getElementsByClassName("current")[0].classList.remove("current");b.transitionEnd&&a.addEventListener(b.transitionEnd,this.afterTransition.bind(this));a.classList.add("current");c.classList.add("current")}};
d.Carousel.prototype.next=function(){this._items.getElementsByClassName("current")[0].nextElementSibling?this.goTo(this._items.getElementsByClassName("current")[0].nextElementSibling,this._bubbles.getElementsByClassName("current")[0].nextElementSibling):this.goTo(this._items.children[0],this._bubbles.children[0])};d.Carousel.prototype.previous=function(){this._items.getElementsByClassName("current")[0].previousElementSibling?this.goTo(this._items.getElementsByClassName("current")[0].previousElementSibling,
this._bubbles.getElementsByClassName("current")[0].previousElementSibling):this.goTo(this._items.children[this._items.children.length-1],this._bubbles.children[this._bubbles.children.length-1])};d.Carousel.prototype.goToIndex=function(a){this.goTo(this._items.children[a],this._bubbles.children[a])};d.Carousel.prototype.setTouchHandlers=function(){var a=this;this._carousel.addEventListener("touchstart",function(c){a.touchStart.x=c.touches[0].pageX;a.touchStart.y=c.touches[0].pageY},false);this._carousel.addEventListener("touchmove",
function(c){var e,b;a.touchEnd.x=c.touches[0].pageX;a.touchEnd.y=c.touches[0].pageY;e=a.touchStart.x-a.touchEnd.x;b=a.touchStart.y-a.touchEnd.y;e<0&&(e=-e);b<0&&(b=-b);if(e>b){c.preventDefault();e>20&&c.stopPropagation()}},false);this._carousel.addEventListener("touchend",function(){var c,b,d,f;c=d=a.touchStart.x-a.touchEnd.x;b=f=a.touchStart.y-a.touchEnd.y;c<0&&(d=-c);b<0&&(f=-b);d>f&&(c>20?a.next():c<20&&a.previous())},false)};d.Carousel.prototype.setHandlers=function(){var a=this;h.call(this._bubbles.children,
function(b){b.addEventListener("click",function(b){a.goToIndex(a._bubbleNodeList.indexOf(this));b.stopPropagation()},false)});this._controls.getElementsByClassName("next")[0].addEventListener("click",function(){a.next()},false);this._controls.getElementsByClassName("previous")[0].addEventListener("click",function(){a.previous()},false);"ontouchstart"in g.documentElement&&this.setTouchHandlers()};d.Carousel.prototype.init=function(){this.setHandlers();if(this.autoplay){b.clearTimeout(this._timeout);
this._timeout=b.setTimeout(this.next.bind(this),this.delay)}}})(document,window,window.NVS);
